info:
  contact: {}
  license: {}
paths:
  /test:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: 通过接收username返回字符串
      operationId: test-api
      parameters:
      - description: 用户名
        in: path
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            Token:
              description: qwerty
              type: string
          schema:
            type: string
      summary: 测试api
swagger: "2.0"
